parameters:
    acme_demo.sitemap.listener.class: Main\SiteBundle\Listener\SitemapListener

services:
    my.sitemap.listener:
        class: %acme_demo.sitemap.listener.class%
        arguments: [@router, @doctrine.orm.entity_manager]
        tags: [{name: "presta.sitemap.listener"}]